// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Index = require("./index");

var idontwork = Index.idontwork;

var iwork = Index.iwork;

exports.idontwork = idontwork;
exports.iwork = iwork;
/* idontwork Not a pure module */
