// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var IndexI = require("./indexI.bs.js");

Curry._1(IndexI.idontwork, {
      TAG: /* Ok */0,
      _0: 12
    });

Curry._1(IndexI.iwork, undefined);

/*  Not a pure module */
